### ISSUE TITLE
Possibility to filter the ical export

### ISSUE THREAD

**Issue by mammuth** [ckarrie/ckw-csgo#1]
It looks like there is no way to filter for certain teams when using the ical export, correct?
Eg. if I were only interested in the CS main and Equipa teams, I'd still receive calendar events for Fortnite, LoL, etc.

Given how many different teams there are and that most of us are probably only interested in a subset of the games, it would be a great addition!

Thanks for building this! (Funnily, I once built [the same thing](https://github.com/mammuth/hltv-api) but the HLTV Go scraper I based it on broke and I never got into fixing it...)

**Comment by ckarrie** [comment]
Yeah, the game category is quite new. Going to add a ICS filter. Scraping HLTV is really a mess.

**Comment by ckarrie** [comment]
Use following URL to get CS Events only. A more flexible filter is on my todo list.

https://wannspieltbig.de/feeds/big_upcoming_cs.ics

**Comment by mammuth** [comment]
Amazing, thank you! 💯
